version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    groups:
      npm-prod:
        dependency-type: "production"
      npm-dev:
        dependency-type: "development"

  - package-ecosystem: "cargo"
    directory: "/server"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    groups:
      cargo-server-non-major:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      cargo-server-major:
        patterns:
          - "*"
        update-types:
          - "major"

  - package-ecosystem: "cargo"
    directory: "/src-tauri"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    groups:
      cargo-tauri-non-major:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      cargo-tauri-major:
        patterns:
          - "*"
        update-types:
          - "major"
